### ISSUE TITLE
Duplicate incoming MDC values can lead to MDC leaks

### ISSUE THREAD

**Issue by sarahgerweck** [Log4s/log4s#10]
Discovered by @dyross: if you send in two copies of the same value in your `MDC.withMDC` call, the MDC will retain the value when the `withMDC` block exits.

Example:

```scala
    MDC.withMDC("a" -> "1", "a" -> "1") {}
    // MDC will still contain "a"
```

**Comment by hosamaly** [comment]
Can this issue be marked as resolved, @sarahgerweck?

**Comment by sarahgerweck** [comment]
Yes, this was resolved in November. Thanks for the reminder!
