### ISSUE TITLE
Nested context with MDC.withCtx?

### ISSUE THREAD

**Issue by macalinao** [Log4s/log4s#16]
Is this possible? I'd love to be able to pass in some nested JSON.

**Comment by sarahgerweck** [comment]
How would this work, precisely? Can you show an example of what you'd like to pass in and how that would update the context?

You can certainly have JSON as the value of one of your keys.

It's worth noting that this library is really just SLF4J underneath, which is really just something like Logback or Log4j underneath. Whatever Log4s does, it needs to translate into something that the ultimate logger will understand.

**Comment by macalinao** [comment]
That makes sense. I'll look more into Logback, which is what I'm using, and see if it's possible there.
