### ISSUE TITLE
Expose TestAppender in new test library

### ISSUE THREAD

**Issue by david-mcgillicuddy-ovo** [Log4s/log4s#20]
The class `TestAppender` is very useful for verifying that the right things are logged during structured logging. However because of its location in `src/test` it doesn't seem to be exposed so I am re-implementing identical functionality.

Perhaps it could be in a `log4s-testing` library that's used by `log4s`? It'd just be a matter of moving the code and adding the import back to `log4s` itself. 

If there's interest I'm happy to make the code change myself but the repo would need to be created here as part of the same project.

**Comment by sarahgerweck** [comment]
@david-mcgillicuddy-ovo this seems reasonable. It would be tied specifically to Logback (at least with the current implementation). That's not the end of the world, as the desire to support scala.js has also been leading me in a direction away from the original scope of being strictly a wrapper around SLF4J that Scala-friendly that added as little runtime overhead as possible. (Though this still remains the primary objective.)

**Comment by david-mcgillicuddy-ovo** [comment]
@sarahgerweck The new library could be log4s-logback-test or something, I don't think it ties log4s itself to Logback.

That's great news thanks, I look forward to it.

**Comment by david-mcgillicuddy-ovo** [comment]
Actually while I'm making requests, I found myself defining a
```
  def clearQueue(): Unit = synchronized {
    events.clear()
  }
```
in `TestAppender`, so that I don't have to worry about tests making sure to dequeue all their queued messages or interfering with other tests. Is there a better way do to that?

**Comment by sarahgerweck** [comment]
@david-mcgillicuddy-ovo I'll think about it when I'm building this feature. I'm thinking that the right thing is probably to add a method that takes a callback, which can ensure not only that the queue is empty at the start, but also prevent the running of concurrent tests against the same appender, which won't really work.

**Comment by sarahgerweck** [comment]
@david-mcgillicuddy-ovo just a note that I haven't forgotten about this. My first attempt at remodularizing this didn't work quite as well as I'd hoped, and then I simultaneously got busy & sick. 😷 I'm hoping I'll get back to finish this soon.

**Comment by david-mcgillicuddy-ovo** [comment]
Thanks for the update, I hope you feel better soon. As mentioned I just implemented my own version of this very hastily so I'm not blocked or anything don't worry. When the change happens it just means I can delete my own code and replace it with a better constructed version.

**Comment by david-mcgillicuddy-ovo** [comment]
Hello again, we recently started using MDCs in our code, and naturally I tried to test them using my version of this class. However I found that the `ILoggingEvent`s received by `AppenderBase.append` came with `getMDCPropertyMap` equal to null - as you can see in the debugger screenshot below.

I did have success adding the current MDC manually during `append` though  - 
```
  private def addEvent(event: ILoggingEvent): Unit = synchronized {
    val _ = events += new LoggingEventWithMdc(event, JMDC.getCopyOfContextMap)
  }
```
Where `LoggingEventWithMdc` implements `ILoggingEvent` and just wraps together the base `ILoggingEvent` and a `java.util.Map[String, String]` overriding only `getMDCPropertyMap` - I couldn't think of a better solution to overriding a single read-only property in an interface.

Thoughts? Better solutions?

<img width="512" alt="image" src="https://user-images.githubusercontent.com/34236977/36857004-512408de-1d6f-11e8-9c28-a7eb5eca8caa.png">

**Comment by sarahgerweck** [comment]
Hi @david-mcgillicuddy-ovo, I'm going to leave two comments since there are two issues here.

RE your question about the MDC, I'm not entirely sure why you'd have an MDC property map with a null MDC unless the code that's actually doing the logging is somehow not setting the MDC. Have you enabled output logging with a `{%X}` in your layout string to verify that you're actually setting the MDC that you think you are?

I was just explaining to someone else that you have to be quite careful when setting the MDC if you're using `Future`s or other multithreaded work pools because the MDC in frameworks like Logback & Log4j is based on `ThreadLocal` variables. See #21 for a longer discussion of the issues involved.

Based on what you're seeing, I decided to add some (admittedly micro–) tests to make sure that I could capture the MDC correctly in my mock appender, and that it would persist even after the MDC was cleared. You can see these [new tests](https://github.com/Log4s/log4s/blob/c7fb1c70e63320eb117d21745ce2b9437bdf25c8/core/src/test/scala/org/log4s/LoggerSpec.scala#L119-L147) in my code, which I think are analogous to what you're trying to do?

**Comment by sarahgerweck** [comment]
Regarding the original request here, I've factored out the classes used to create a mock appender and improved them a bit. They're now published in parallel as `log4s-testing` and there's a [section in the README](https://github.com/Log4s/log4s#testing). 

@david-mcgillicuddy-ovo, I think you're already familiar with the existing code. However, there is a new `TestAppender.withAppender()` wrapper that automatically does a bit of cleanup for you, and there's a `LoggedEvent` compile-time wrapper that is a bit more Scala friendly.

**Comment by sarahgerweck** [comment]
As noted above, this is currently a Logback-only mechanism, but it's still aligned with the mission of this library to provide thin & efficient wrappers that make standards-based logging more convenient and idiomatic to Scala.

If anybody comes across this and wishes there were an analogous appender bridge for Log4j or Log4j2, I'd be happy to take a look at a PR. It should be easy to do something analogous with a slightly different interface. I believe Logback is currently the most popular logger for Scala-JVM, but I've heard good things about Log4j 2 and the position of Log4s is to be as agnostic as possible about the choice of the ultimate logging implementation.
