### ISSUE TITLE
Release for 2.13.0-M5

### ISSUE THREAD

**Issue by aeons** [Log4s/log4s#29]
Would it be possible to cut a release for 2.13.0-M5?

**Comment by SethTisue** [comment]
looks like work is underway at https://github.com/Log4s/log4s/commit/3e2519ec65d3666f69b6ac8ecdfa362884bb537d

**Comment by aeons** [comment]
Yep, looks like there's only a release missing :)

**Comment by sarahgerweck** [comment]
Version 1.7.0 just went out with commit 92e7c642c0372b950656edcd1587d36dff23071b.
It's been pushed to Sonatype and should hit Maven Central within 15 minutes or so.

**Comment by SethTisue** [comment]
scala/make-release-notes@51909b2daac4f1c74bc95eb742d011fc2309349b
