### ISSUE TITLE
Scala 2.13 support: drop the RCs?

### ISSUE THREAD

**Issue by rossabaker** [Log4s/log4s#37]
I started working on Scala 2.13.0.  scalatest has not published a 3.0.x release for Scala 2.13.  We might have to upgrade to scalatest-3.1, which will also introduce scalatestplus-scalacheck.  Wrangling all these versions for the Scala 2.13.0-RC series doesn't seem like a good use of time.  I propose we drop 2.13.0-RC1, 2.13.0-RC2, and 2.13.0-RC3 as part of the 2.13 support PR.  Any objections?

**Comment by rossabaker** [comment]
Wow, scalatest_2.13-3.0.8 has just appeared.  That should be enough to unblock a PR, but I stand by the drop-the-RCs proposal.

**Comment by sarahgerweck** [comment]
Yeah, there's no reason to keep the RCs in there.
