### ISSUE TITLE
Resolve Travis concurrent-test issue

### ISSUE THREAD

**Issue by sarahgerweck** [Log4s/log4s#39]
There's a longstanding issue where Travis [builds](https://travis-ci.org/Log4s/log4s/builds/542385881) have their [tests fail](https://travis-ci.org/Log4s/log4s/jobs/542385883), typically with this message:

    org.scalajs.testcommon.RPCCore$RPCException: java.lang.IllegalStateException: Can't have multiple test appenders

It's not clear exactly what causes this. Commit 06f5525e6eaef78194e42883d4a20076158c8c9a was an attempt to prevent duplicate initialization, but it didn't work. It's possible this is a Scala.js bug of some kind that never occurs on the JDK.

Any proposed solution here would need to ensure that the functionality of `+test` in the SBT shell works as well. (E.g., skipping initialization altogether will cause that to fail.)

**Comment by sarahgerweck** [comment]
Note @rossabaker, I think this is fixed (properly) now.

**Comment by rossabaker** [comment]
:tada: The fix makes sense, and [Travis is happy](https://travis-ci.org/Log4s/log4s/builds/544386515).
