### ISSUE TITLE
Requirements Question

### ISSUE THREAD

**Issue by xionglian** [Log4s/log4s#47]
not  just add the dependency as described above.
![image](https://user-images.githubusercontent.com/16647947/72711665-67c72080-3ba4-11ea-9e32-1e73abad29d6.png)
![image](https://user-images.githubusercontent.com/16647947/72711733-934a0b00-3ba4-11ea-8d86-c4382e141bc6.png)

**Comment by rossabaker** [comment]
Sorry for the slow reply.  The answer should be in the link two lines down.
