### ISSUE TITLE
ScalaJS 1.0.0 Support

### ISSUE THREAD

**Issue by matthughes** [Log4s/log4s#48]
Any hope of getting this in?  1.0.0 is only compatible with 2.12.10 and 2.13+.  I assume you still want to keep support for older Scala versions or could those be dropped now?

**Comment by rossabaker** [comment]
I defer to @sarahgerweck, but the scala.js support has always been "experimental."  Is there any reason we can't publish scala.js for 1.x, just on 2.12 and 2.13, and keep the JVM versions as is?

**Comment by ebruchez** [comment]
There is a pull request for this at https://github.com/Log4s/log4s/pull/49
