### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by rossabaker** [Log4s/log4s#59]
Travis CI's OSS offering is withering.  We should move to GitHub Actions.  We can mitigate most of the pain with sbt-github-actions.

**Comment by rossabaker** [comment]
Noticed this banner in the last release cycle:

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

I think we're still free, but [the blog post](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) exceeds my pandemic-shortened attention span.

**Comment by sullis** [comment]
Work in progress:
https://github.com/Log4s/log4s/pull/79
